name: 📋 Spec Request
description: Request a technical specification for a feature or improvement
title: "[SPEC] "
labels: ["needs-spec", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Request a technical specification from the CoStudy AI Bot. This is useful for:
        - Existing features that lack documentation
        - Planned features that need detailed specs
        - Complex improvements requiring technical planning

        The AI bot will automatically generate a comprehensive specification.

  - type: textarea
    id: feature-overview
    attributes:
      label: Feature Overview
      description: What feature or improvement needs a specification?
      placeholder: |
        Feature: Real-time collaboration
        Purpose: Allow multiple students to work together
        Scope: Document editing and chat
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What are the key requirements or constraints?
      placeholder: |
        Must support:
        - Multiple concurrent users
        - Real-time updates
        - Conflict resolution

        Technical constraints:
        - Must work on mobile
        - Should integrate with existing auth system
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe the user journeys or use cases
      placeholder: |
        As a student, I want to...
        As a professor, I need to...
        When multiple users...
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex is this feature?
      options:
        - Simple - Single component/page
        - Medium - Multiple components
        - Complex - Multiple pages/systems
        - Very Complex - Cross-cutting concerns
    validations:
      required: true

  - type: textarea
    id: tech-stack
    attributes:
      label: Technical Preferences
      description: Any specific technologies or approaches?
      placeholder: |
        Prefer using: WebSockets, React hooks
        Avoid: Polling, legacy components
        Database: New tables needed

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related issues, docs, or examples
      placeholder: |
        Related issue: #123
        Similar to: https://example.com
        Docs: ...

  - type: checkboxes
    id: spec-sections
    attributes:
      label: Requested Spec Sections
      description: What should the specification include?
      options:
        - label: User interface designs and mockups
        - label: Database schema changes
        - label: API endpoints and contracts
        - label: Security considerations
        - label: Performance requirements
        - label: Test coverage requirements
        - label: Deployment considerations

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for related specs
          required: true
        - label: I have provided sufficient detail for spec generation
          required: true
