name: Auto Push
# Enables Claude Code to trigger pushes via workflow dispatch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to push'
        required: true
        default: 'main'
      commit_message:
        description: 'Commit message'
        required: true
      files:
        description: 'Files to add (comma-separated paths, or "all" for all changes)'
        required: true
        default: 'all'

jobs:
  push-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "Claude Code"
          git config user.email "claude@anthropic.com"

      - name: Stage files
        run: |
          if [ "${{ github.event.inputs.files }}" = "all" ]; then
            git add -A
          else
            IFS=',' read -ra FILES <<< "${{ github.event.inputs.files }}"
            for file in "${FILES[@]}"; do
              git add "$file"
            done
          fi

      - name: Commit changes
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "${{ github.event.inputs.commit_message }}

          🤖 Generated with [Claude Code](https://claude.com/claude-code)

          Co-Authored-By: Claude <noreply@anthropic.com>"

      - name: Push changes
        run: |
          git push origin ${{ github.event.inputs.branch }}

      - name: Trigger Vercel deployment check
        run: |
          # Wait a bit for Vercel to pick up the push
          sleep 10

          # Trigger the deployment monitor workflow
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deployment-monitor.yml/dispatches \
            -d '{"ref":"main"}'
