name: 🤖 AI Spec Writer

on:
  issues:
    types: [labeled, opened]

jobs:
  generate-spec:
    if: contains(github.event.issue.labels.*.name, 'needs-spec')
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd ops
          pip install -r requirements.txt

      - name: Generate specification
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          cd ops
          python scripts/spec_writer.py --issue ${{ github.event.issue.number }}

      - name: Post completion message
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Specification generated successfully by CoStudy AI Bot!'
            })

      - name: Post error message
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Failed to generate specification. Please check the workflow logs or contact a maintainer.'
            })
