name: Weekly Blog Post Generation

on:
  schedule:
    # Every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      topic:
        description: 'Blog post topic (optional - uses trending topic if not provided)'
        required: false
        type: string

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install openai anthropic requests

      - name: Create output directory
        run: |
          mkdir -p content/generated

      - name: Generate blog post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          # Use manual topic if provided, otherwise use default
          TOPIC="${{ github.event.inputs.topic }}"
          if [ -z "$TOPIC" ]; then
            TOPIC="Education Technology Insights for $(date +'%B %Y')"
          fi

          echo "Generating blog post about: $TOPIC"

          python3 ops/scripts/ultimate_content_generator.py blog \
            --topic "$TOPIC" \
            --keywords "education,technology,students,collaboration" \
            --ai claude-opus \
            --output "content/generated/blog_$(date +%Y%m%d).json"

      - name: Generate hero image
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Extract headline for image prompt
          HEADLINE=$(jq -r '.content.headline // "Professional education technology"' content/generated/blog_$(date +%Y%m%d).json)

          python3 ops/scripts/ultimate_content_generator.py image \
            --prompt "$HEADLINE - modern, professional, educational setting" \
            --ai dalle3-hd \
            --output "content/generated/image_$(date +%Y%m%d).json"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            content: Weekly blog post generated for $(date +%Y-%m-%d)

            Auto-generated blog post with AI content generator.
            Review and merge to publish.

            🤖 Generated with [Claude Code](https://claude.com/claude-code)
          branch: auto/blog-$(date +%Y%m%d)
          title: '[Auto] Weekly Blog Post - $(date +%B %d, %Y)'
          body: |
            ## 📝 Automated Blog Post Generation

            **Topic:** ${{ github.event.inputs.topic || 'Education Technology Insights' }}
            **Generated:** $(date)

            ### 📄 Files Created:
            - `content/generated/blog_$(date +%Y%m%d).json` - Blog post content
            - `content/generated/image_$(date +%Y%m%d).json` - Hero image

            ### 📊 Content Preview:
            ```json
            $(cat content/generated/blog_$(date +%Y%m%d).json | jq -r '.content.headline, .content.meta_description' | head -5)
            ```

            ### 💰 Cost:
            **Blog:** $$(cat content/generated/blog_$(date +%Y%m%d).json | jq -r '.cost')
            **Image:** $$(cat content/generated/image_$(date +%Y%m%d).json | jq -r '.cost')

            ### ✅ Next Steps:
            1. Review blog content for accuracy
            2. Check SEO optimization
            3. Verify image quality
            4. Merge to publish

            ---
            🤖 Auto-generated by Weekly Blog Generation workflow
          labels: |
            automated
            content
            blog
          assignees: brock-nelson

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ Weekly Blog Generation Failed',
              body: `The automated blog generation workflow failed.

              **Workflow:** ${context.workflow}
              **Run:** ${context.runNumber}
              **Date:** ${new Date().toISOString()}

              [View workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId})

              Please check the workflow logs and fix any issues.`,
              labels: ['bug', 'automated', 'high-priority']
            })
